# Generated by Django 4.1 on 2022-12-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('institucion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
